/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Igor Tretyakov (https://sketchfab.com/vdv77)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/low-poly-city-pack-7f671f35e9ad4149b83451a3a92a6e2e
title: low poly city pack
*/
import { useControls, button } from 'leva'
import { useThree } from 'react-three-fiber'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SmartCity({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/smart-city.gltf')

  const gl = useThree((state) => state.gl)
  useControls({
    screenshot: button(() => {
      const link = document.createElement('a')
      link.setAttribute('download', 'canvas.png')
      const imgUrl = gl.domElement.toDataURL('image/png').replace('image/png', 'image/octet-stream');
      link.setAttribute('href', gl.domElement.toDataURL('image/png').replace('image/png', 'image/octet-stream'));
      link.click();
    })
  })


  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-450.46, 368.52, 2623.86]}>
            <mesh geometry={nodes['������������_������_1_1__13'].geometry} material={materials['1_1__13']} />
            <mesh geometry={nodes['������������_������_1_1_����������������_5'].geometry} material={materials.material_15} />
            <mesh geometry={nodes['������������_������_1_1_����������������2_6'].geometry} material={materials.material_16} />
            <mesh geometry={nodes['������������_������_1_1_����������������11_13'].geometry} material={materials.material_3} />

            {/* 도로 */}
            <mesh geometry={nodes['������������_������_1_1_����������������5_1'].geometry} material={materials.material_4} />
            <mesh geometry={nodes['������������_������_1_1_����������������27_13'].geometry} material={materials.material_5} />
            <mesh geometry={nodes['������������_������_1_1_����������������19_13'].geometry} material={materials.material_6} />
            <mesh geometry={nodes['������������_������_1_1_����������������6_13'].geometry} material={materials.material_7} />
            <mesh geometry={nodes['������������_������_1_1_����������������12_13'].geometry} material={materials.material_8} />

            {/* 공항 */}
            <mesh geometry={nodes['������������_������_1_1_����������������17_13'].geometry} material={materials.material_9} />
            <mesh geometry={nodes['������������_������_1_1_����������������10_13'].geometry} material={materials.material_11} />
            <mesh geometry={nodes['������������_������_1_1_����������������3_2'].geometry} material={materials.material_12} />
            <mesh geometry={nodes['������������_������_1_1_����������������1_7'].geometry} material={materials.material_17} />
            <mesh geometry={nodes['������������_������_1_1_����������������26_8'].geometry} material={materials.material_18} />
            <mesh geometry={nodes['������������_������_1_1_����������������7_13'].geometry} material={materials.material_19} />
            <mesh geometry={nodes['������������_������_1_1_����������������8_13'].geometry} material={materials.material_20} />
            <mesh geometry={nodes['������������_������_1_1_����������������11_13_1'].geometry} material={materials['.11_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������6_13_1'].geometry} material={materials['.6_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������1_13'].geometry} material={materials['.1_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������5_13'].geometry} material={materials['.5_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������3_13'].geometry} material={materials['.3_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������2_13'].geometry} material={materials['.2_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������9_13'].geometry} material={materials.material_27} />
            <mesh geometry={nodes['������������_������_1_1_����������������12_13_1'].geometry} material={materials['.12_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������10_13_1'].geometry} material={materials['.10_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������13_13'].geometry} material={materials.material_30} />
            <mesh geometry={nodes['������������_������_1_1_����������������14_13'].geometry} material={materials.material_31} />
            <mesh geometry={nodes['������������_������_1_1_����������������9_13_1'].geometry} material={materials['.9_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������9_13_2'].geometry} material={materials['.9_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������9_13_3'].geometry} material={materials['.9_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������9_13_4'].geometry} material={materials['.9_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������9_13_5'].geometry} material={materials['.9_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������9_13_6'].geometry} material={materials['.9_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������9_13_7'].geometry} material={materials['.9_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������9_13_8'].geometry} material={materials['.9_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������9_13_9'].geometry} material={materials['.9_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������9_13_10'].geometry} material={materials['.9_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������4_13'].geometry} material={materials.material_33} />

            {/* 건물 */}
            <mesh geometry={nodes['������������_������_1_1_����������������38_13'].geometry} material={materials.material_34} />
            <mesh geometry={nodes['������������_������_1_1_����������������21_13'].geometry} material={materials.material_35} />
            <mesh geometry={nodes['������������_������_1_1_����������������29_13'].geometry} material={materials.material_36} />
            <mesh geometry={nodes['������������_������_1_1_����������������14_13_1'].geometry} material={materials['.14_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������42_13'].geometry} material={materials.material_38} />
            <mesh geometry={nodes['������������_������_1_1_����������������20_13'].geometry} material={materials.material_39} />
            <mesh geometry={nodes['������������_������_1_1_����������������7_13_1'].geometry} material={materials['.7_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������8_13_1'].geometry} material={materials['.8_0']} />

            {/* 42~48 전기차 주유소 있음 */}
            <mesh geometry={nodes['������������_������_1_1_����������������16_13'].geometry} material={materials.material_42} />
            <mesh geometry={nodes['������������_������_1_1_����������������35_13'].geometry} material={materials.material_43} />
            <mesh geometry={nodes['������������_������_1_1_����������������34_13'].geometry} material={materials.material_44} />
            <mesh geometry={nodes['������������_������_1_1_����������������36_13'].geometry} material={materials.material_45} />
            <mesh geometry={nodes['������������_������_1_1_����������������30_13'].geometry} material={materials.material_46} />
            <mesh geometry={nodes['������������_������_1_1_����������������23_13'].geometry} material={materials.material_47} />
            <mesh geometry={nodes['������������_������_1_1_����������������24_13'].geometry} material={materials.material_48} />
            <mesh geometry={nodes['������������_������_1_1_����������������9_13_11'].geometry} material={materials['.9_1']} />
            <mesh geometry={nodes['������������_������_1_1_����������������43_13'].geometry} material={materials.material_50} />
            <mesh geometry={nodes['������������_������_1_1_����������������13_13_1'].geometry} material={materials['.13_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������13_13_2'].geometry} material={materials['.13_0']} />

            {/* 나무 윗쪽 */}
            <mesh geometry={nodes['������������_������_1_1_����������������33_13'].geometry} material={materials.material_52} />
            <mesh geometry={nodes['������������_������_1_1_����������������15_13'].geometry} material={materials.material_53} />
            <mesh geometry={nodes['������������_������_1_1_����������������18_13'].geometry} material={materials.material_54} />
            <mesh geometry={nodes['������������_������_1_1_����������������22_13'].geometry} material={materials.material_55} />
            <mesh geometry={nodes['������������_������_1_1_����������������25_13'].geometry} material={materials.material_56} />
            <mesh geometry={nodes['������������_������_1_1_����������������25_13_1'].geometry} material={materials.material_56} />
            <mesh geometry={nodes['������������_������_1_1_����������������31_13'].geometry} material={materials.material_57} />
            <mesh geometry={nodes['������������_������_1_1_����������������1_13_1'].geometry} material={materials['.1_1']} />
            <mesh geometry={nodes['������������_������_1_1_����������������39_13'].geometry} material={materials.material_59} />
            <mesh geometry={nodes['������������_������_1_1_����������������40_13'].geometry} material={materials.material_60} />
            <mesh geometry={nodes['������������_������_1_1_����������������13_13_3'].geometry} material={materials['.13_1']} />
            <mesh geometry={nodes['������������_������_1_1_����������������11_13_2'].geometry} material={materials['.11_1']} />
            <mesh geometry={nodes['������������_������_1_1_����������������10_13_2'].geometry} material={materials['.10_1']} />
            <mesh geometry={nodes['������������_������_1_1_����������������5_13_1'].geometry} material={materials['.5_1']} />
            <mesh geometry={nodes['������������_������_1_1_����������������7_13_2'].geometry} material={materials['.7_1']} />
            <mesh geometry={nodes['������������_������_1_1_����������������15_13_1'].geometry} material={materials['.15_0']} />
            <mesh geometry={nodes['������������_������_1_1_����������������3_13_1'].geometry} material={materials['.3_1']} />
            <mesh geometry={nodes['������������_������_1_1_����������������1_13_2'].geometry} material={materials['.1_2']} />
            <mesh geometry={nodes['������������_������_1_1_����������������8_13_2'].geometry} material={materials['.8_1']} />
            <mesh geometry={nodes['������������_������_1_1_����������������14_13_2'].geometry} material={materials['.14_1']} />
            <mesh geometry={nodes['������������_������_1_1_����������������2_13_1'].geometry} material={materials['.2_1']} />
            <mesh geometry={nodes['������������_������_1_1_����������������_4'].geometry} material={materials.material_14} />
            <mesh geometry={nodes['������������_������_1_1_����������������1_13_3'].geometry} material={materials['.1_3']} />
            <mesh geometry={nodes['������������_������_1_1_����������������1_0'].geometry} material={materials['.1_3']} />
            <mesh geometry={nodes['������������_������_1_1_����������������_13'].geometry} material={materials.material} />
            <mesh geometry={nodes['������������_������_1_1_����������������_13_1'].geometry} material={materials.material_10} />
            <mesh geometry={nodes['������������_������_1_1_����������������2_3'].geometry} material={materials['.2_2']} />
          </group>

          {/* 비행기 */}
          {/* <group position={[-6382.16, 5991.59, 597.05]} rotation={[0, -1.3, 0]}>
            <mesh geometry={nodes['������������_������_1_����������������_0'].geometry} material={materials.material_72} />
            <mesh geometry={nodes['������������_������_1_����������������2_0'].geometry} material={materials['.2_3']} />
            <mesh geometry={nodes['������������_������_1_����������������1_0'].geometry} material={materials['.1_4']} />
            <mesh geometry={nodes['������������_������_1__0'].geometry} material={materials['1_1__13']} />
          </group> */}
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/smart-city.gltf')
