/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Fabian van Dorst (https://sketchfab.com/FabianvanDorst)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/solar-panel-ff765abe2d324c91899541b43cc40c72
title: Solar-Panel
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { TransformControls } from '@react-three/drei'

export default function Solor( props ) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/solor.gltf')
  return (
    <TransformControls enabled={props.orbit} showX={props.orbit} showZ={props.orbit} showY={props.orbit}>  
    <group ref={group} dispose={null} scale={10}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Sweep_default_0.geometry} material={materials['default']} />
          <mesh geometry={nodes.Cap_1_default_0.geometry} material={materials.default_0} />
          <mesh geometry={nodes.Cap_2_default_0.geometry} material={materials.default_1} />
          <mesh geometry={nodes.Cap_1_1_default_0.geometry} material={materials.default_2} />
          <mesh geometry={nodes.Cap_2_1_default_0.geometry} material={materials.default_3} />
          <mesh geometry={nodes.Cap_1_2_default_0.geometry} material={materials.default_4} />
          <mesh geometry={nodes.Cap_2_2_default_0.geometry} material={materials.default_5} />
          <mesh geometry={nodes.Cap_1_3_default_0.geometry} material={materials.default_6} />
          <mesh geometry={nodes.Cap_2_3_default_0.geometry} material={materials.default_7} />
          <mesh geometry={nodes.Cube7_default_0.geometry} material={materials.default_8} />
        </group>
      </group>
    </group>
    </TransformControls>
  )
}

useGLTF.preload('/solor.gltf')
