/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: VioletBoom (https://sketchfab.com/violetboom)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tree-lp-c76ca4c065824faca1006b07252b1c17
title: tree LP
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { TransformControls } from '@react-three/drei'

export default function Tree( props ) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/tree.gltf')
  return (
  <TransformControls enabled={props.orbit} showX={props.orbit} showZ={props.orbit} showY={props.orbit}>  
    <group ref={group} dispose={null} scale={0.2}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0, 0, 1.32]}>
          <mesh geometry={nodes.Cylinder_0.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Cylinder_1.geometry} material={materials['Material.002']} />
        </group>
        <group position={[-0.11, -9.19, 10.17]} scale={3.73}>
          <mesh geometry={nodes.Icosphere001_0.geometry} material={materials['Material.002']} />
        </group>
        <group position={[0, -9.16, 1.32]}>
          <mesh geometry={nodes.Cylinder001_0.geometry} material={materials['Material.001']} />
        </group>
      </group>
    </group>
    </TransformControls>
  )
}

useGLTF.preload('/tree.gltf')
